export const SET_COURSES_LIST = 'COURSE/GET_COURSES_LIST';
export const ADD_NEW_COURSE = 'COURSE/ADD_NEW_COURSE';
export const REMOVE_COURSE = 'COURSE/REMOVE_COURSE';
export const UPDATE_COURSE = 'COURSE/UPDATE_COURSE';
